### ISSUE TITLE
Sending Data with send() Method Always Results in 0 Value

### ISSUE THREAD

**Issue by sagumudradi** [bastengao/react-native-usb-serialport-for-android#15]
When attempting to send data using the send() method from the library, the sent value is always 0, regardless of the input.

![Screenshot from 2024-03-02 15-55-36](https://github.com/bastengao/react-native-usb-serialport-for-android/assets/38550539/bbbf3835-81dc-4807-a7ea-e47eae55b65a)

**Comment by TiMMaTTiee** [comment]
@sagumudradi I think I have the same issue, what did you do to fix this?
