### ISSUE TITLE
Cannot receive data 

### ISSUE THREAD

**Issue by NortacYWang** [bastengao/react-native-usb-serialport-for-android#2]
Hello, I updated the version to 0.4.1, and I tried to send the command but it seems the onReceived function is not working, this is my code: 

```
async function getConnection() {
    const devices = await UsbSerialManager.list();
    console.log("devices", devices);
    try {
      await UsbSerialManager.tryRequestPermission(2002);
      const usbSerialport = await UsbSerialManager.open(2002, {
        baudRate: 38400,
        parity: 0,
        dataBits: 8,
        stopBits: 1,
      });

      const sub = usbSerialport.onReceived(event => {
        console.log(event.deviceId, event.data);
      });
      // unsubscribe
      // sub.remove();

      await usbSerialport.send('AT+OCT');

      usbSerialport.close();
    } catch (err) {
      console.log(err);
    }
  }
```

I logged the device, it did find my device, but the onReceived function never logs the received data
![image](https://user-images.githubusercontent.com/96532687/221448779-2829e928-7bc9-42f8-8f44-e020cfd59878.png)

also I got some warning like this: 
![image](https://user-images.githubusercontent.com/96532687/221448468-fccebfee-3232-4518-9fa3-2730c26131e5.png)

could you please help me with this ?

Thank you very much !

**Comment by bastengao** [comment]
You must send data with **HEX** format

**Comment by NortacYWang** [comment]
> You must send data with **HEX** format

Hello, Basten,  I have also tried HEX format: "00FF", and we expect a string "invalid commad" back, but still no data back from onReceived function....

**Comment by bastengao** [comment]
I mean you should format you data to HEX, not directly send "00FF", "00FF" is a sample.

**Comment by NortacYWang** [comment]
Thanks, I found we need to add "\r" to the end of string to receive correct response.

**Comment by zanaaaa** [comment]
Hello, could you help me please? 
I am using serial communication through a RS-232 Serial cable and I'm transmitting data to my react native app in BYTES.
How do you mean "format your data to HEX"? where? how? I cannot change the format on the transmitting device, and react native app is my receiving device.

**Comment by bastengao** [comment]
The data sending to device and got from device both format with hex. Don't worry the hex format is only on application layer. Device will receive bytes.

**Comment by zanaaaa** [comment]
@bastengao Thank you very much. Could you know why I'm getting the same data twice (no matter its size), on every receive (everytime onReceived is triggered) ? 
For example,
 const sub = usbSerialport.onReceived((event) => {
        console.log(event.data);
});


If i send HEX 32 30, the console.log outputs this value twice.
And this is happening on every receive.

**Comment by zanaaaa** [comment]
Thank you very much @bastengao .
