### ISSUE TITLE
Getting Error while running in Android 12

### ISSUE THREAD

**Issue by xeen0** [bastengao/react-native-usb-serialport-for-android#4]
Getting following error when I am trying UsbSerialManager.list() function in Android 12, but when I use in lower versions it's working fine.
![image](https://user-images.githubusercontent.com/12679388/235296801-29a53ea3-7482-47df-902d-70ef0597b19a.png)

@bastengao Can you check this issue.

**Comment by paulojoao** [comment]
Same error here

**Comment by bastengao** [comment]
Try version v0.5.0
